## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
